name: Build ArduPilot

on:
  push:
    paths:
      - ardupilot/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [SITL_x86_64_linux_gnu, SITL_arm_linux_gnueabihf]
        vehicletype: [AntennaTracker, Copter, Plane, Rover, Sub, Blimp]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push linux2rest Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./ardupilot
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ardupilot-$(echo "${{ matrix.vehicletype }}" | awk '{print tolower($0)}'):latest
          build-args: |
            VEHICLETYPE=${{ matrix.vehicletype }}

