name: Build Linux2Rest

on:
  workflow_dispatch:
  push:
    paths:
      - linux2rest/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push linux2rest Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./linux2rest
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/linux2rest:latest

